"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username\
[](fg:color_bg3)\
$directory\
[](fg:color_bg3)\
$git_branch\
$git_status\
[](fg:color_bg3)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_bg3)\
$time\
[ ](fg:color_bg3)\
 """

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[os]
disabled = false
style = "fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "fg:color_fg0"
style_root = "fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
format = '[[ $symbol $branch ](fg:color_fg0)]($style)'

[git_status]
format = '[[($all_status$ahead_behind )](fg:color_fg0)]($style)'

[nodejs]
symbol = ""
format = '[[ $symbol( $version) ](fg:color_fg0)]($style)'

[c]
symbol = " "
format = '[[ $symbol( $version) ](fg:color_fg0)]($style)'

[rust]
symbol = ""
format = '[[ $symbol( $version) ](fg:color_fg0)]($style)'

[golang]
symbol = ""
format = '[[ $symbol( $version) ](fg:color_fg0)]($style)'

[php]
symbol = ""
format = '[[ $symbol( $version) ](fg:color_fg0)]($style)'

[java]
symbol = " "
format = '[[ $symbol( $version) ](fg:color_fg0)]($style)'

[kotlin]
symbol = ""
format = '[[ $symbol( $version) ](fg:color_fg0)]($style)'

[haskell]
symbol = ""
format = '[[ $symbol( $version) ](fg:color_fg0)]($style)'

[python]
symbol = ""
format = '[[ $symbol ](fg:color_fg0)]($style)'

[docker_context]
symbol = ""
format = '[[ $symbol( $context) ](fg:#83a598)]($style)'

[conda]
format = '[[ $symbol( $environment) ](fg:#83a598)]($style)'

[time]
disabled = false
time_format = "%R"
format = '[[  $time ](fg:color_fg0)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
