import = [
    "~/.config/alacritty/current-colors.toml"
]

[window]
opacity = 0.90

[font.normal]
family = "MesloLGS NF"

[env]
TERM = "xterm-256color"

[cursor]
blink_interval = 750

[cursor.style]
shape = "Block"
blinking = "Always"
